# Generated by Django 4.0.4 on 2022-05-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_image_1_post_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
