# Generated by Django 4.0.4 on 2022-05-23 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_1', models.ImageField(blank=True, upload_to='photos/posts')),
                ('image_2', models.ImageField(blank=True, upload_to='photos/posts')),
                ('image_3', models.ImageField(blank=True, upload_to='photos/posts')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
