# Generated by Django 4.0.4 on 2022-05-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_welcomenote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_1',
            new_name='title_image',
        ),
    ]
